name: gitfolio
description: "A Flutter portfolio app with clean architecture for GitHub profiles."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.6
  provider: ^6.1.2
  flutter_hooks: ^0.20.5
  equatable: ^2.0.5
  
  # HTTP & Network
  http: ^1.2.2
  
  # Functional Programming
  dartz: ^0.10.1
  
  # Local Storage
  shared_preferences: ^2.3.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  pdf: ^3.11.0
  path_provider: ^2.1.4
  share_plus: ^7.2.2
  
  # URL & WebView
  url_launcher: ^6.3.1
  webview_flutter: ^4.9.0
  flutter_web_auth_2: ^3.0.1
  
  # Formatting & Utils
  intl: ^0.19.0
  fl_chart: ^0.69.0
  qr_flutter: ^4.1.0
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Downgraded to be compatible with Dart 3.5.0

flutter:
  uses-material-design: true

